### ISSUE TITLE
about joern 

### ISSUE THREAD

**Issue by Nero0113** [WIP2022/DataSampling4DLVD#1]
![image](https://user-images.githubusercontent.com/94276947/221839978-b308df02-f874-45a5-a1f0-77212c2bece6.png)
When I try to run build.sbt, it returns an error like this, please help me solve it

**Comment by nimasteryang** [comment]
Update joern.zip at [#a01d6cb](https://github.com/WIP2022/DataSampling4DLVD/commit/a01d6cb246bfd4d2fd46448821bf457e9513b82a)
